version: '3.2'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5434:5432
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vendingmachine
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d:rw
      - /opt/mysql_data:/var/lib/mysql

  keycloak:
    build:
      context: ../
      dockerfile: Dockerfile
    labels:
      container-name: keycloak
    command:
      - "-b 0.0.0.0 --debug *:8787"
    environment:
      # KEYCLOAK_IMPORT: /opt/realm-files/btcmarkets.json
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      #KEYCLOAK_USER: admin
      #KEYCLOAK_PASSWORD: admin
      #JAVA_OPTS: -Xms512m -Xmx1024m
      # Uncomment the line below if you want to specify JDBC parameters.
      # The parameter below is just an example, and it shouldn't be used in production without knowledge.
      # It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 9000:8080
      - 8787:8787
   # volumes:
    #  - type: "bind"
     #   source: "./realm-files"
      #  target: "/opt/realm-files"
    depends_on:
      - postgres
